### ISSUE TITLE
💡 [REQUEST] - Shorthand flags for commands such as -f for --force

### ISSUE THREAD

**Issue by tylercritchlow** [brodycritchlow/winch#5]
### Start Date

11/27/23

### Summary

shorthand flags for the command line commands so that we don't have to do `winch install --force kalker` instead we can do `winch install -f kalker`

### Basic Example

not applicable at this time

### Drawbacks

Not aware of any drawbacks

**Comment by brodycritchlow** [comment]
Already implemented
